# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/operation_profile_lib/",
        "doc_host": "https://{user}.github.io",
        "git_url": "https://github.com/{user}/operation_profile_interface/",
        "lib_path": "operation_profile_lib",
    },
    "syms": {
        "operation_profile_lib.operation_profile_pb2": {},
        "operation_profile_lib.operation_profile_pb2_grpc": {},
        "operation_profile_lib.operation_profile_structure": {
            "operation_profile_lib.operation_profile_structure.Location": (
                "operation_profile_structure.html#location",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Location.__init__": (
                "operation_profile_structure.html#location.__init__",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Location.to_dict": (
                "operation_profile_structure.html#location.to_dict",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Location.to_dict_scalar": (
                "operation_profile_structure.html#location.to_dict_scalar",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Location.to_proto": (
                "operation_profile_structure.html#location.to_proto",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.OperationPoint": (
                "operation_profile_structure.html#operationpoint",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.OperationPoint.__init__": (
                "operation_profile_structure.html#operationpoint.__init__",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.OperationPoint.to_dict": (
                "operation_profile_structure.html#operationpoint.to_dict",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.OperationPoint.to_dict_scalar": (
                "operation_profile_structure.html#operationpoint.to_dict_scalar",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.OperationPoint.to_proto": (
                "operation_profile_structure.html#operationpoint.to_proto",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Weather": (
                "operation_profile_structure.html#weather",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Weather.__init__": (
                "operation_profile_structure.html#weather.__init__",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Weather.get_weather_at_index": (
                "operation_profile_structure.html#weather.get_weather_at_index",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Weather.to_dict": (
                "operation_profile_structure.html#weather.to_dict",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Weather.to_dict_scalar": (
                "operation_profile_structure.html#weather.to_dict_scalar",
                "operation_profile_lib/operation_profile_structure.py",
            ),
            "operation_profile_lib.operation_profile_structure.Weather.to_proto": (
                "operation_profile_structure.html#weather.to_proto",
                "operation_profile_lib/operation_profile_structure.py",
            ),
        },
    },
}
