# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation_profile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17operation_profile.proto\x12\x10operationProfile"/\n\x08Location\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01"\xaa\x02\n\x07Weather\x12!\n\x19significant_wave_height_m\x18\x01 \x01(\x01\x12\x1a\n\x12mean_wave_period_s\x18\x02 \x01(\x01\x12\x1a\n\x12wave_direction_deg\x18\x03 \x01(\x01\x12\x1a\n\x12wind_speed_m_per_s\x18\x04 \x01(\x01\x12\x1a\n\x12wind_direction_deg\x18\x05 \x01(\x01\x12#\n\x1bocean_current_speed_m_per_s\x18\x06 \x01(\x01\x12#\n\x1bocean_current_direction_deg\x18\x07 \x01(\x01\x12\x1d\n\x15\x61ir_temperature_deg_c\x18\x08 \x01(\x01\x12#\n\x1bsea_water_temperature_deg_c\x18\t \x01(\x01"\xe8\x01\n\x0eOperationPoint\x12\x19\n\x11timestamp_seconds\x18\x01 \x01(\x03\x12\x10\n\x08speed_kn\x18\x02 \x01(\x01\x12\x13\n\x0bheading_deg\x18\x03 \x01(\x01\x12\x17\n\x0f\x61uxiliary_power\x18\x04 \x01(\x01\x12/\n\x07weather\x18\x05 \x01(\x0b\x32\x19.operationProfile.WeatherH\x00\x88\x01\x01\x12\x31\n\x08location\x18\x06 \x01(\x0b\x32\x1a.operationProfile.LocationH\x01\x88\x01\x01\x42\n\n\x08_weatherB\x0b\n\t_locationb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "operation_profile_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _LOCATION._serialized_start = 45
    _LOCATION._serialized_end = 92
    _WEATHER._serialized_start = 95
    _WEATHER._serialized_end = 393
    _OPERATIONPOINT._serialized_start = 396
    _OPERATIONPOINT._serialized_end = 628
# @@protoc_insertion_point(module_scope)
