# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/ship_model_lib/",
        "doc_host": "https://developer.github.io",
        "git_url": "https://github.com/developer/https://SintefOceanEnergySystem@dev.azure.com/SintefOceanEnergySystem/DesignLab/_git/ship_model_lib/",
        "lib_path": "ship_model_lib",
    },
    "syms": {
        "ship_model_lib.added_resistance": {
            "ship_model_lib.added_resistance.AddedResistance": (
                "addedresistance.html#addedresistance",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistance._get_encounter_angle_deg": (
                "addedresistance.html#addedresistance._get_encounter_angle_deg",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistance._get_froude_number": (
                "addedresistance.html#addedresistance._get_froude_number",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistance._get_wave_spectrum": (
                "addedresistance.html#addedresistance._get_wave_spectrum",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistance._omega_high_lim": (
                "addedresistance.html#addedresistance._omega_high_lim",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistance._validate_the_condition": (
                "addedresistance.html#addedresistance._validate_the_condition",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistance.get_added_resistance_newton": (
                "addedresistance.html#addedresistance.get_added_resistance_newton",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM": (
                "addedresistance.html#addedresistancebysnnm",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM.__post_init__": (
                "addedresistance.html#addedresistancebysnnm.__post_init__",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._a3": (
                "addedresistance.html#addedresistancebysnnm._a3",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_a1": (
                "addedresistance.html#addedresistancebysnnm._get_a1",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_a1_following_sea": (
                "addedresistance.html#addedresistancebysnnm._get_a1_following_sea",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_a1_head_sea": (
                "addedresistance.html#addedresistancebysnnm._get_a1_head_sea",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_a2": (
                "addedresistance.html#addedresistancebysnnm._get_a2",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_a2_following_sea": (
                "addedresistance.html#addedresistancebysnnm._get_a2_following_sea",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_added_resistance_component_in_frequency_and_wave_direction": (
                "addedresistance.html#addedresistancebysnnm._get_added_resistance_component_in_frequency_and_wave_direction",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_added_resistance_for_a_single_point": (
                "addedresistance.html#addedresistancebysnnm._get_added_resistance_for_a_single_point",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_added_resistance_for_a_single_point_double_integration": (
                "addedresistance.html#addedresistancebysnnm._get_added_resistance_for_a_single_point_double_integration",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_angular_distribution": (
                "addedresistance.html#addedresistancebysnnm._get_angular_distribution",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_draft_coefficient": (
                "addedresistance.html#addedresistancebysnnm._get_draft_coefficient",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_function_to_integrate": (
                "addedresistance.html#addedresistancebysnnm._get_function_to_integrate",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_length_of_entrance": (
                "addedresistance.html#addedresistancebysnnm._get_length_of_entrance",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_length_of_run": (
                "addedresistance.html#addedresistancebysnnm._get_length_of_run",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_non_dimensional_wave_resistance": (
                "addedresistance.html#addedresistancebysnnm._get_non_dimensional_wave_resistance",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_non_dimensional_wave_resistance_due_to_motion": (
                "addedresistance.html#addedresistancebysnnm._get_non_dimensional_wave_resistance_due_to_motion",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_non_dimensional_wave_resistance_due_to_reflection": (
                "addedresistance.html#addedresistancebysnnm._get_non_dimensional_wave_resistance_due_to_reflection",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._get_omega_normalized": (
                "addedresistance.html#addedresistancebysnnm._get_omega_normalized",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._t_deep": (
                "addedresistance.html#addedresistancebysnnm._t_deep",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._trim_angle_rad": (
                "addedresistance.html#addedresistancebysnnm._trim_angle_rad",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM._validate_the_condition": (
                "addedresistance.html#addedresistancebysnnm._validate_the_condition",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM.angle_for_shadowed_part_aft_deg": (
                "addedresistance.html#addedresistancebysnnm.angle_for_shadowed_part_aft_deg",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM.angle_for_shadowed_part_forward_deg": (
                "addedresistance.html#addedresistancebysnnm.angle_for_shadowed_part_forward_deg",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySNNM.get_added_resistance_newton": (
                "addedresistance.html#addedresistancebysnnm.get_added_resistance_newton",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySeaMarginCurve": (
                "addedresistance.html#addedresistancebyseamargincurve",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySeaMarginCurve._wave_height_to_sea_margin_interpolation_function": (
                "addedresistance.html#addedresistancebyseamargincurve._wave_height_to_sea_margin_interpolation_function",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceBySeaMarginCurve.get_sea_margin_percent": (
                "addedresistance.html#addedresistancebyseamargincurve.get_sea_margin_percent",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2": (
                "addedresistance.html#addedresistancebystawave2",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2._get_alpha1": (
                "addedresistance.html#addedresistancebystawave2._get_alpha1",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2._get_f1": (
                "addedresistance.html#addedresistancebystawave2._get_f1",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2._get_raw": (
                "addedresistance.html#addedresistancebystawave2._get_raw",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2._validate_the_condition": (
                "addedresistance.html#addedresistancebystawave2._validate_the_condition",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2.get_added_resistance_newton": (
                "addedresistance.html#addedresistancebystawave2.get_added_resistance_newton",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2.get_resistance_component_in_frequency": (
                "addedresistance.html#addedresistancebystawave2.get_resistance_component_in_frequency",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2.get_resistance_due_to_motion": (
                "addedresistance.html#addedresistancebystawave2.get_resistance_due_to_motion",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceByStaWave2.get_resistance_due_to_reflection": (
                "addedresistance.html#addedresistancebystawave2.get_resistance_due_to_reflection",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceWindITTC": (
                "addedresistance.html#addedresistancewindittc",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceWindITTC.__post_init__": (
                "addedresistance.html#addedresistancewindittc.__post_init__",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceWindITTC._get_relative_wind_angle_and_speed": (
                "addedresistance.html#addedresistancewindittc._get_relative_wind_angle_and_speed",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.AddedResistanceWindITTC.get_added_resistance_newton": (
                "addedresistance.html#addedresistancewindittc.get_added_resistance_newton",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.JONSWAPSpectrumITTC1984": (
                "addedresistance.html#jonswapspectrumittc1984",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.JONSWAPSpectrumITTC1984._a_coefficient": (
                "addedresistance.html#jonswapspectrumittc1984._a_coefficient",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.JONSWAPSpectrumITTC1984._b_coefficient": (
                "addedresistance.html#jonswapspectrumittc1984._b_coefficient",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.JONSWAPSpectrumITTC1984._get_exponent_for_peak_shape_parameter": (
                "addedresistance.html#jonswapspectrumittc1984._get_exponent_for_peak_shape_parameter",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.JONSWAPSpectrumITTC1984.get_spectral_density_omega": (
                "addedresistance.html#jonswapspectrumittc1984.get_spectral_density_omega",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.PiersonMoskowitzSpectrumITTC1978": (
                "addedresistance.html#piersonmoskowitzspectrumittc1978",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.PiersonMoskowitzSpectrumITTC1978._a_coefficient": (
                "addedresistance.html#piersonmoskowitzspectrumittc1978._a_coefficient",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.PiersonMoskowitzSpectrumITTC1978._b_coefficient": (
                "addedresistance.html#piersonmoskowitzspectrumittc1978._b_coefficient",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.PiersonMoskowitzSpectrumITTC1978.get_spectral_density_omega": (
                "addedresistance.html#piersonmoskowitzspectrumittc1978.get_spectral_density_omega",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.get_wave_frequency": (
                "addedresistance.html#get_wave_frequency",
                "ship_model_lib/added_resistance.py",
            ),
            "ship_model_lib.added_resistance.get_wave_length": (
                "addedresistance.html#get_wave_length",
                "ship_model_lib/added_resistance.py",
            ),
        },
        "ship_model_lib.calm_water_resistance": {
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBase": (
                "calmwaterresistance.html#calmwaterresistancebase",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBase._speed_to_y_interpolation_function": (
                "calmwaterresistance.html#calmwaterresistancebase._speed_to_y_interpolation_function",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBase._y_to_speed_interpolation_function": (
                "calmwaterresistance.html#calmwaterresistancebase._y_to_speed_interpolation_function",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedPowerCurve": (
                "calmwaterresistance.html#calmwaterresistancebyspeedpowercurve",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedPowerCurve.__init__": (
                "calmwaterresistance.html#calmwaterresistancebyspeedpowercurve.__init__",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedPowerCurve.get_power_from_speed": (
                "calmwaterresistance.html#calmwaterresistancebyspeedpowercurve.get_power_from_speed",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedPowerCurve.get_speed_from_power": (
                "calmwaterresistance.html#calmwaterresistancebyspeedpowercurve.get_speed_from_power",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedPowerCurve.power_ref_kw": (
                "calmwaterresistance.html#calmwaterresistancebyspeedpowercurve.power_ref_kw",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedResistanceCurve": (
                "calmwaterresistance.html#calmwaterresistancebyspeedresistancecurve",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedResistanceCurve.__init__": (
                "calmwaterresistance.html#calmwaterresistancebyspeedresistancecurve.__init__",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedResistanceCurve.get_resistance_from_speed": (
                "calmwaterresistance.html#calmwaterresistancebyspeedresistancecurve.get_resistance_from_speed",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedResistanceCurve.get_speed_from_resistance": (
                "calmwaterresistance.html#calmwaterresistancebyspeedresistancecurve.get_speed_from_resistance",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceBySpeedResistanceCurve.resistance_ref_k_n": (
                "calmwaterresistance.html#calmwaterresistancebyspeedresistancecurve.resistance_ref_k_n",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase.__init__": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase.__init__",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._c_a": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._c_a",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._c_aas": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._c_aas",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._ct_to_rt": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._ct_to_rt",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._fn_critical": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._fn_critical",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_app": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_app",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_f": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_f",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r_bt": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r_bt",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r_bt_min": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r_bt_min",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r_min": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r_min",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r_standard": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r_standard",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r_standard_from_coeff": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r_standard_from_coeff",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_c_r_standard_min": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_c_r_standard_min",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_coeff_for_high_froude_number_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_coeff_for_high_froude_number_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_fn": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_fn",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_k_fr_high_froude_number_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_k_fr_high_froude_number_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_r_th": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_r_th",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_total_resistance_max": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_total_resistance_max",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_total_resistance_mean": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_total_resistance_mean",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_total_resistance_mean_minsaas": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_total_resistance_mean_minsaas",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._get_total_resistance_min": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._get_total_resistance_min",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_ao": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_ao",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_bt": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_bt",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_l": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_l",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_lb": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_lb",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_ll": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_ll",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_pr": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_pr",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_shape_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_shape_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._k_tr": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._k_tr",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._lfn_length_froude_number": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._lfn_length_froude_number",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase._to_c_r": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase._to_c_r",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase.get_resistance_from_speed": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase.get_resistance_from_speed",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase.get_reynolds_number": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase.get_reynolds_number",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase.get_speed_from_resistance": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase.get_speed_from_resistance",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase.t_draft": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase.t_draft",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachBase.wetted_surface_area": (
                "calmwaterresistance.html#calmwaterresistancehollenbachbase.wetted_surface_area",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewBallastDraft": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewballastdraft",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewBallastDraft._get_c_r_min": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewballastdraft._get_c_r_min",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewBallastDraft._get_c_r_standard_min": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewballastdraft._get_c_r_standard_min",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewBallastDraft._get_coeff_for_high_froude_number_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewballastdraft._get_coeff_for_high_froude_number_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewDesignDraft": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewdesigndraft",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewDesignDraft.__init__": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewdesigndraft.__init__",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachSingleScrewDesignDraft._get_coeff_for_high_froude_number_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachsinglescrewdesigndraft._get_coeff_for_high_froude_number_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachTwinScrewDesignDraft": (
                "calmwaterresistance.html#calmwaterresistancehollenbachtwinscrewdesigndraft",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachTwinScrewDesignDraft.__init__": (
                "calmwaterresistance.html#calmwaterresistancehollenbachtwinscrewdesigndraft.__init__",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachTwinScrewDesignDraft._get_c_r_bt": (
                "calmwaterresistance.html#calmwaterresistancehollenbachtwinscrewdesigndraft._get_c_r_bt",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachTwinScrewDesignDraft._get_coeff_for_high_froude_number_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachtwinscrewdesigndraft._get_coeff_for_high_froude_number_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.CalmWaterResistanceHollenbachTwinScrewDesignDraft._k_shape_factor": (
                "calmwaterresistance.html#calmwaterresistancehollenbachtwinscrewdesigndraft._k_shape_factor",
                "ship_model_lib/calm_water_resistance.py",
            ),
            "ship_model_lib.calm_water_resistance.kn_to_m_per_s": (
                "calmwaterresistance.html#kn_to_m_per_s",
                "ship_model_lib/calm_water_resistance.py",
            ),
        },
        "ship_model_lib.data.create_table": {},
        "ship_model_lib.machinery": {
            "ship_model_lib.machinery.Curve": (
                "machinery.html#curve",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Curve.add_point": (
                "machinery.html#curve.add_point",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Curve.get_curve_plot": (
                "machinery.html#curve.get_curve_plot",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Curve.to_x_array": (
                "machinery.html#curve.to_x_array",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Curve.to_y_array": (
                "machinery.html#curve.to_y_array",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.EmissionFactor": (
                "machinery.html#emissionfactor",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.EmissionFactor.get_emission_kg_per_h": (
                "machinery.html#emissionfactor.get_emission_kg_per_h",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.EmissionFactor.get_emission_plot": (
                "machinery.html#emissionfactor.get_emission_plot",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.EmissionFactor.has_scalar_factor": (
                "machinery.html#emissionfactor.has_scalar_factor",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.EmissionFactor.interpolate_factor": (
                "machinery.html#emissionfactor.interpolate_factor",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Emissions": (
                "machinery.html#emissions",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Emissions.__add__": (
                "machinery.html#emissions.__add__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelByMassFraction": (
                "machinery.html#fuelbymassfraction",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelByMassFraction.__post_init__": (
                "machinery.html#fuelbymassfraction.__post_init__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelByMassFraction.get_co_2_curve": (
                "machinery.html#fuelbymassfraction.get_co_2_curve",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelByMassFraction.lhv_mj_per_kg": (
                "machinery.html#fuelbymassfraction.lhv_mj_per_kg",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelConsumption": (
                "machinery.html#fuelconsumption",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelConsumption.__add__": (
                "machinery.html#fuelconsumption.__add__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelConsumption.__init__": (
                "machinery.html#fuelconsumption.__init__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.FuelConsumption.total_fuel_consumption": (
                "machinery.html#fuelconsumption.total_fuel_consumption",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.LoadInput": (
                "machinery.html#loadinput",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachineryResult": (
                "machinery.html#machineryresult",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachineryResult.__add__": (
                "machinery.html#machineryresult.__add__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySubsystemSimple": (
                "machinery.html#machinerysubsystemsimple",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySubsystemSimple.get_machinery_result": (
                "machinery.html#machinerysubsystemsimple.get_machinery_result",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySystem": (
                "machinery.html#machinerysystem",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySystem.__post_init__": (
                "machinery.html#machinerysystem.__post_init__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySystem.get_machinery_result": (
                "machinery.html#machinerysystem.get_machinery_result",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySystem.has_electric_system": (
                "machinery.html#machinerysystem.has_electric_system",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySystem.has_mechanical_system": (
                "machinery.html#machinerysystem.has_mechanical_system",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.MachinerySystemResult": (
                "machinery.html#machinerysystemresult",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.Point": (
                "machinery.html#point",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerLoad": (
                "machinery.html#powerload",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerLoad.__post_init__": (
                "machinery.html#powerload.__post_init__",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerLoad._efficiency_curve_interpolator": (
                "machinery.html#powerload._efficiency_curve_interpolator",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerLoad._has_scalar_efficiency": (
                "machinery.html#powerload._has_scalar_efficiency",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerLoad.get_efficiency": (
                "machinery.html#powerload.get_efficiency",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerLoad.get_power_in_kw": (
                "machinery.html#powerload.get_power_in_kw",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSource": (
                "machinery.html#powersource",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSource.get_emissions_kg_per_h": (
                "machinery.html#powersource.get_emissions_kg_per_h",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSource.get_fuel_consumption_kg_per_h": (
                "machinery.html#powersource.get_fuel_consumption_kg_per_h",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSource.get_machinery_result": (
                "machinery.html#powersource.get_machinery_result",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSource.get_specific_fuel_consumption_g_per_kwh": (
                "machinery.html#powersource.get_specific_fuel_consumption_g_per_kwh",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithEfficiency": (
                "machinery.html#powersourcewithefficiency",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithEfficiency._engine_efficiency_curve_interpolator": (
                "machinery.html#powersourcewithefficiency._engine_efficiency_curve_interpolator",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithEfficiency._has_scalar_efficiency": (
                "machinery.html#powersourcewithefficiency._has_scalar_efficiency",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithEfficiency.get_specific_fuel_consumption_g_per_kwh": (
                "machinery.html#powersourcewithefficiency.get_specific_fuel_consumption_g_per_kwh",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithSpecificFuelConsumption": (
                "machinery.html#powersourcewithspecificfuelconsumption",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithSpecificFuelConsumption._has_scalar_specific_fuel_consumption": (
                "machinery.html#powersourcewithspecificfuelconsumption._has_scalar_specific_fuel_consumption",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithSpecificFuelConsumption._specific_fuel_consumption_curve_interpolator": (
                "machinery.html#powersourcewithspecificfuelconsumption._specific_fuel_consumption_curve_interpolator",
                "ship_model_lib/machinery.py",
            ),
            "ship_model_lib.machinery.PowerSourceWithSpecificFuelConsumption.get_specific_fuel_consumption_g_per_kwh": (
                "machinery.html#powersourcewithspecificfuelconsumption.get_specific_fuel_consumption_g_per_kwh",
                "ship_model_lib/machinery.py",
            ),
        },
        "ship_model_lib.propulsor": {
            "ship_model_lib.propulsor.OpenWaterPropellerCurvePoint": (
                "propulsor.html#openwaterpropellercurvepoint",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.Propulsor": (
                "propulsor.html#propulsor",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.Propulsor.get_propulsor_data_from_vessel_speed_rps": (
                "propulsor.html#propulsor.get_propulsor_data_from_vessel_speed_rps",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.Propulsor.get_propulsor_data_from_vessel_speed_thrust": (
                "propulsor.html#propulsor.get_propulsor_data_from_vessel_speed_thrust",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries": (
                "propulsor.html#propulsordatabseries",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries.__init__": (
                "propulsor.html#propulsordatabseries.__init__",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries._generate_kt_kq_curve": (
                "propulsor.html#propulsordatabseries._generate_kt_kq_curve",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries._get_kq_bseries": (
                "propulsor.html#propulsordatabseries._get_kq_bseries",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries._get_kt_bseries": (
                "propulsor.html#propulsordatabseries._get_kt_bseries",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries._re_correction_bseries": (
                "propulsor.html#propulsordatabseries._re_correction_bseries",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataBseries._re_correction_ittc78": (
                "propulsor.html#propulsordatabseries._re_correction_ittc78",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater": (
                "propulsor.html#propulsordataopenwater",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.__init__": (
                "propulsor.html#propulsordataopenwater.__init__",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater._function_to_solve_for_n_rps": (
                "propulsor.html#propulsordataopenwater._function_to_solve_for_n_rps",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater._get_advance_ratio": (
                "propulsor.html#propulsordataopenwater._get_advance_ratio",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater._get_initial_guess_for_n_rps": (
                "propulsor.html#propulsordataopenwater._get_initial_guess_for_n_rps",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater._get_thrust_reduction": (
                "propulsor.html#propulsordataopenwater._get_thrust_reduction",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater._get_wake_velocity_m_per_s": (
                "propulsor.html#propulsordataopenwater._get_wake_velocity_m_per_s",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_efficiency_open_water": (
                "propulsor.html#propulsordataopenwater.get_efficiency_open_water",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_kq": (
                "propulsor.html#propulsordataopenwater.get_kq",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_kt": (
                "propulsor.html#propulsordataopenwater.get_kt",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_propulsor_data_from_vessel_speed_rps": (
                "propulsor.html#propulsordataopenwater.get_propulsor_data_from_vessel_speed_rps",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_propulsor_data_from_vessel_speed_thrust": (
                "propulsor.html#propulsordataopenwater.get_propulsor_data_from_vessel_speed_thrust",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_thrust_newton": (
                "propulsor.html#propulsordataopenwater.get_thrust_newton",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_thrust_reduced": (
                "propulsor.html#propulsordataopenwater.get_thrust_reduced",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.get_torque_newton_meter": (
                "propulsor.html#propulsordataopenwater.get_torque_newton_meter",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataOpenWater.plot_open_water_curves": (
                "propulsor.html#propulsordataopenwater.plot_open_water_curves",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataScalar": (
                "propulsor.html#propulsordatascalar",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataScalar.__init__": (
                "propulsor.html#propulsordatascalar.__init__",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataScalar.get_propulsor_data_from_vessel_speed_rps": (
                "propulsor.html#propulsordatascalar.get_propulsor_data_from_vessel_speed_rps",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataScalar.get_propulsor_data_from_vessel_speed_thrust": (
                "propulsor.html#propulsordatascalar.get_propulsor_data_from_vessel_speed_thrust",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorDataScalar.get_propulsor_thrust_from_shaft_power": (
                "propulsor.html#propulsordatascalar.get_propulsor_thrust_from_shaft_power",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorOperatingPoint": (
                "propulsor.html#propulsoroperatingpoint",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorOperatingPoint.efficiency_hull": (
                "propulsor.html#propulsoroperatingpoint.efficiency_hull",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorOperatingPoint.shaft_power_kw": (
                "propulsor.html#propulsoroperatingpoint.shaft_power_kw",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.PropulsorOperatingPoint.wake_fraction_factor": (
                "propulsor.html#propulsoroperatingpoint.wake_fraction_factor",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.ReCorrection": (
                "propulsor.html#recorrection",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.WakeFractionThrustDeductionFactorPoint": (
                "propulsor.html#wakefractionthrustdeductionfactorpoint",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.kn_to_m_per_s": (
                "propulsor.html#kn_to_m_per_s",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.m_per_s_to_kn": (
                "propulsor.html#m_per_s_to_kn",
                "ship_model_lib/propulsor.py",
            ),
            "ship_model_lib.propulsor.rps_to_rad_per_s": (
                "propulsor.html#rps_to_rad_per_s",
                "ship_model_lib/propulsor.py",
            ),
        },
        "ship_model_lib.ship_dimensions": {
            "ship_model_lib.ship_dimensions.ShipDimensionsAddedResistance": (
                "ship_dimensions.html#shipdimensionsaddedresistance",
                "ship_model_lib/ship_dimensions.py",
            ),
            "ship_model_lib.ship_dimensions.ShipDimensionsAddedResistance.__post_init__": (
                "ship_dimensions.html#shipdimensionsaddedresistance.__post_init__",
                "ship_model_lib/ship_dimensions.py",
            ),
            "ship_model_lib.ship_dimensions.ShipDimensionsAddedResistance.tm_draft_mid_m": (
                "ship_dimensions.html#shipdimensionsaddedresistance.tm_draft_mid_m",
                "ship_model_lib/ship_dimensions.py",
            ),
            "ship_model_lib.ship_dimensions.ShipDimensionsHollenbachSingleScrew": (
                "ship_dimensions.html#shipdimensionshollenbachsinglescrew",
                "ship_model_lib/ship_dimensions.py",
            ),
            "ship_model_lib.ship_dimensions.ShipDimensionsHollenbachTwinScrew": (
                "ship_dimensions.html#shipdimensionshollenbachtwinscrew",
                "ship_model_lib/ship_dimensions.py",
            ),
        },
        "ship_model_lib.ship_model": {
            "ship_model_lib.ship_model.HullData": (
                "ship_model.html#hulldata",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.HullOperatingPoint": (
                "ship_model.html#hulloperatingpoint",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.HullOperatingPoint.__init__": (
                "ship_model.html#hulloperatingpoint.__init__",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.HullOperatingPoint.__repr__": (
                "ship_model.html#hulloperatingpoint.__repr__",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.HullOperatingPoint.total_resistance_newton": (
                "ship_model.html#hulloperatingpoint.total_resistance_newton",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.HullOperatingPoint.total_towing_power_kw": (
                "ship_model.html#hulloperatingpoint.total_towing_power_kw",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.PropulsorData": (
                "ship_model.html#propulsordata",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipDescription": (
                "ship_model.html#shipdescription",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel": (
                "ship_model.html#shipmodel",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel.__init__": (
                "ship_model.html#shipmodel.__init__",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel._fill_weather_with_default": (
                "ship_model.html#shipmodel._fill_weather_with_default",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel._get_calm_water_power_speed_curve_interpolator": (
                "ship_model.html#shipmodel._get_calm_water_power_speed_curve_interpolator",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel._iterate_ship_power": (
                "ship_model.html#shipmodel._iterate_ship_power",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel.get_ship_performance_data_from_operating_point": (
                "ship_model.html#shipmodel.get_ship_performance_data_from_operating_point",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel.get_ship_performance_data_from_power": (
                "ship_model.html#shipmodel.get_ship_performance_data_from_power",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipModel.get_ship_performance_data_from_speed": (
                "ship_model.html#shipmodel.get_ship_performance_data_from_speed",
                "ship_model_lib/ship_model.py",
            ),
            "ship_model_lib.ship_model.ShipPerformanceData": (
                "ship_model.html#shipperformancedata",
                "ship_model_lib/ship_model.py",
            ),
        },
        "ship_model_lib.types": {},
        "ship_model_lib.utility": {
            "ship_model_lib.utility.Interpolated1DValue": (
                "utility.html#interpolated1dvalue",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.Interpolated1DValue.__init__": (
                "utility.html#interpolated1dvalue.__init__",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.Interpolated1DValue.cause": (
                "utility.html#interpolated1dvalue.cause",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.Interpolated1DValue.is_extrapolated": (
                "utility.html#interpolated1dvalue.is_extrapolated",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.InterpolatedValue": (
                "utility.html#interpolatedvalue",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.InterpolatedValue.__init__": (
                "utility.html#interpolatedvalue.__init__",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.InterpolatedValue.cause": (
                "utility.html#interpolatedvalue.cause",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.InterpolatedValue.is_extrapolated": (
                "utility.html#interpolatedvalue.is_extrapolated",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.Result": (
                "utility.html#result",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.Result.__init__": (
                "utility.html#result.__init__",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.Result.append_warning": (
                "utility.html#result.append_warning",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.WarningMessage": (
                "utility.html#warningmessage",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.WarningType": (
                "utility.html#warningtype",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.get_froude_number": (
                "utility.html#get_froude_number",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.get_interpolation_1d_function": (
                "utility.html#get_interpolation_1d_function",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.get_speed_kn_from_froude_number": (
                "utility.html#get_speed_kn_from_froude_number",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.kn_to_m_per_s": (
                "utility.html#kn_to_m_per_s",
                "ship_model_lib/utility.py",
            ),
            "ship_model_lib.utility.m_per_s_to_kn": (
                "utility.html#m_per_s_to_kn",
                "ship_model_lib/utility.py",
            ),
        },
    },
}
