on:
    push:
      branches:
        - main
  
permissions:
  contents: write
  pull-requests: write
  id-token: write 

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
      - name: Print the output
        run: echo "The output was $ALLOUTPUT"
        env:
          ALLOUTPUT: ${{ toJSON(steps.release.outputs) }}
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - name: Set up Python
        uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          python-version: "3.12"
      - name: Install pypa/build
        if: ${{ steps.release.outputs.releases_created }}
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build ship_model_lib
        if: ${{ steps.release.outputs.ship_model_lib--release_created }}
        run: python3 -m build
        working-directory: ship_model_lib
      - name: Publish ship_model_lib to PyPI
        if: ${{ steps.release.outputs.ship_model_lib--release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ship_model_lib/dist
