name: Run nbdev_test on all projects

on:
  # Runs on pushes to any branch
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - operation_profile_lib
          - ship_model_lib
          - ship_performance_service_interface

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run nbdev_test
        run: |
          cd ${{ matrix.project }}
          nbdev_test --do_print
      
      - name: Check formatting by black
        run: |
          cd ${{ matrix.project }}
          black --check .
